version: "3.6"
services:
  prometheus-service-scanner:
    container_name: prometheus-service-scanner
    build:
      context: .
      dockerfile: Dockerfile
    image: prometheus-service-scanner
    volumes:
      - /mnt/e/prometheus:/data
    restart: unless-stopped
    ports:
      - '9101:3000'
