version: "3.6"
services:
  prometheus-service-scanner:
    container_name: prometheus-service-scanner
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - '9101:3000'
    image: "danielvestol/prometheus-service-scanner"
